title: Installing Crumble software on Windows
hero_image: images/banner.png
description: installing-crumble-software-windows-os description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-08"
steps:
  - title: Installing Crumble software on Windows OS
